title:              Personal Blog
email:              bakhtiar.rasheed56@gmail.com
description:        Blog about my interests, aspirations and opinions.
author:             Bakhtiar Rasheed
baseurl:            "/blog"
url:                "https://bakhtiar56.github.io"

# Social Profiles
twitter_username:   
github_username:    bakhtiar56
facebook_username:  
instagram_username:  
linkedin_username:  bakhtiar-rasheed

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
